# Generated by Django 5.2.4 on 2025-08-05 05:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='부스 이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '체험 부스',
                'verbose_name_plural': '체험 부스들',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='닉네임')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '참여자',
                'verbose_name_plural': '참여자들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='획득 시각')),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='stampapp.booth')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='stampapp.participant')),
            ],
            options={
                'verbose_name': '스탬프 기록',
                'verbose_name_plural': '스탬프 기록들',
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'booth')},
            },
        ),
    ]
